name: DefaultDB
id: DefaultDB
owner: None
version: 0.0.0
config:
  cache: 5m
  compression: 36h
  batching: 5s
  sleep: 10m
  cacheExpiration: 5m
tables:
  - name: DPoolLists
    id: DefaultDB-DPoolLists
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: DPools
    id: DefaultDB-DPools
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: Users
    id: DefaultDB-Users
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: UserTotalDeposits
    id: DefaultDB-UserTotalDeposits
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: Deposits
    id: DefaultDB-Deposits
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: Funders
    id: DefaultDB-Funders
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: FunderTotalInterests
    id: DefaultDB-FunderTotalInterests
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: Fundings
    id: DefaultDB-Fundings
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: MPHHolders
    id: DefaultDB-MPHHolders
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: MPHs
    id: DefaultDB-MPHs
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: Vests
    id: DefaultDB-Vests
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
  - name: FractionalDeposits
    id: DefaultDB-FractionalDeposits
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 5s
    sleep: 10m
    cacheExpiration: 5m
