  name: Proxima
  id: ProximaID
  owner: None
  version: 0.0.0
  config:
    cache: 5m
    compression: 36h
    batching: 500ms
  tables:
  - name: Applications
    id: Proxima-Applications
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 500ms
    sleep: 10m
    cacheExpiration: 5m
  - name: Peers
    id: Proxima-Peers
    version: 0.0.0
    blockNum: 0
    header: Root
    compression: 36h
    batching: 500ms
    sleep: 10m
    cacheExpiration: 5m
