version: "3"
services:
  db__test_node:
    image:
      build:
        context: .
        dockerfile: Dockerfile.test
    depends_on:
      - db
    environment:
        - DB_ADDRESS=db
        - DB_PORT=50051
  db:
    image: chasesmith95/proxima-db-server:latest
    ports:
      - "50051:50051"
