version: "3"
services:
  db_test_node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
        - DB_ADDRESS=db
        - DB_PORT=50051
  db:
    image: chasesmith95/proxima-db-server:latest
    ports:
      - "50051:50051"
