version: '3'
services:
  db_client_test:
    build: '.'
    depends_on:
      - db
    environment:
      - DB_ADDRESS=db
      - DB_PORT=50051
  db:
    image: 'chasesmith95/proxima-db-server:latest'
    restart: unless-stopped
    ports:
      - '50051:50051'
